title: Gustav Nybro - Portfolio

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gustavnybro.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-seo-tag


# color theme for links
theme-color: dark # indigo|yellow|pink|green|stone|

# homepage information
author: Gustav Søndergaard Nybro



# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: \#about
- text: Projects
  permalink: \#projects
- text: Contact
  permalink: \#contact
- text: Blog &#129133;
  permalink: /blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: false
instagram: false
github: https://github.com/Gustav2/
linkedin: https://linkedin.com/in/gustavnybro/
medium: false
google-scholar: false
email: false

